// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegisterManagement.Data;

namespace RegisterManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200115111546_AddedMoreSeedData")]
    partial class AddedMoreSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RegisterManagement.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreated")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateModified")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500,
                            DateCreated = new DateTime(2020, 1, 15, 13, 15, 45, 649, DateTimeKind.Local).AddTicks(3681),
                            DateModified = new DateTime(2020, 1, 15, 13, 15, 45, 651, DateTimeKind.Local).AddTicks(5981),
                            ItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 200,
                            DateCreated = new DateTime(2020, 1, 15, 13, 15, 45, 651, DateTimeKind.Local).AddTicks(6579),
                            DateModified = new DateTime(2020, 1, 15, 13, 15, 45, 651, DateTimeKind.Local).AddTicks(6600),
                            ItemId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 700,
                            DateCreated = new DateTime(2020, 1, 15, 13, 15, 45, 651, DateTimeKind.Local).AddTicks(6618),
                            DateModified = new DateTime(2020, 1, 15, 13, 15, 45, 651, DateTimeKind.Local).AddTicks(6621),
                            ItemId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1000,
                            DateCreated = new DateTime(2020, 1, 15, 13, 15, 45, 651, DateTimeKind.Local).AddTicks(6623),
                            DateModified = new DateTime(2020, 1, 15, 13, 15, 45, 651, DateTimeKind.Local).AddTicks(6626),
                            ItemId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1234,
                            DateCreated = new DateTime(2020, 1, 15, 13, 15, 45, 651, DateTimeKind.Local).AddTicks(6629),
                            DateModified = new DateTime(2020, 1, 15, 13, 15, 45, 651, DateTimeKind.Local).AddTicks(6632),
                            ItemId = 5
                        });
                });

            modelBuilder.Entity("RegisterManagement.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsRefundable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 15.99,
                            IsRefundable = true,
                            Name = "T-Shirt"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 5.9900000000000002,
                            IsRefundable = false,
                            Name = "Underwear"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 60.990000000000002,
                            IsRefundable = true,
                            Name = "Denim jeans"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 99.989999999999995,
                            IsRefundable = true,
                            Name = "Coat"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 19.989999999999998,
                            IsRefundable = true,
                            Name = "Sweater"
                        });
                });

            modelBuilder.Entity("RegisterManagement.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VisaNo")
                        .HasColumnType("text");

                    b.HasKey("PurchaseNo");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseNo = 1,
                            DateModified = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseNo = 2,
                            DateModified = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisaNo = "371349659706917"
                        },
                        new
                        {
                            PurchaseNo = 3,
                            DateModified = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisaNo = "341471579286296"
                        },
                        new
                        {
                            PurchaseNo = 4,
                            DateModified = new DateTime(2019, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseNo = 5,
                            DateModified = new DateTime(2019, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisaNo = "371172473010823"
                        },
                        new
                        {
                            PurchaseNo = 6,
                            DateModified = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisaNo = "340921234554117"
                        },
                        new
                        {
                            PurchaseNo = 7,
                            DateModified = new DateTime(2019, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseNo = 8,
                            DateModified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisaNo = "378666663860619"
                        },
                        new
                        {
                            PurchaseNo = 9,
                            DateModified = new DateTime(2019, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisaNo = "372675903118544"
                        },
                        new
                        {
                            PurchaseNo = 10,
                            DateModified = new DateTime(2019, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisaNo = "346369552078109"
                        },
                        new
                        {
                            PurchaseNo = 11,
                            DateModified = new DateTime(2019, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPurchase = new DateTime(2019, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisaNo = "379811816360062"
                        });
                });

            modelBuilder.Entity("RegisterManagement.Models.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("AmountReturned")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<bool>("Returned")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 54,
                            AmountReturned = 0,
                            ItemId = 1,
                            PurchaseId = 1,
                            Returned = false
                        },
                        new
                        {
                            Id = 2,
                            Amount = 32,
                            AmountReturned = 0,
                            ItemId = 2,
                            PurchaseId = 1,
                            Returned = false
                        },
                        new
                        {
                            Id = 3,
                            Amount = 54,
                            AmountReturned = 0,
                            ItemId = 1,
                            PurchaseId = 2,
                            Returned = false
                        },
                        new
                        {
                            Id = 4,
                            Amount = 32,
                            AmountReturned = 0,
                            ItemId = 2,
                            PurchaseId = 2,
                            Returned = false
                        },
                        new
                        {
                            Id = 5,
                            Amount = 55,
                            AmountReturned = 0,
                            ItemId = 3,
                            PurchaseId = 3,
                            Returned = false
                        },
                        new
                        {
                            Id = 6,
                            Amount = 66,
                            AmountReturned = 0,
                            ItemId = 4,
                            PurchaseId = 3,
                            Returned = false
                        },
                        new
                        {
                            Id = 7,
                            Amount = 16,
                            AmountReturned = 0,
                            ItemId = 5,
                            PurchaseId = 4,
                            Returned = false
                        },
                        new
                        {
                            Id = 8,
                            Amount = 50,
                            AmountReturned = 0,
                            ItemId = 1,
                            PurchaseId = 4,
                            Returned = false
                        },
                        new
                        {
                            Id = 9,
                            Amount = 43,
                            AmountReturned = 0,
                            ItemId = 2,
                            PurchaseId = 5,
                            Returned = false
                        },
                        new
                        {
                            Id = 10,
                            Amount = 9,
                            AmountReturned = 0,
                            ItemId = 3,
                            PurchaseId = 5,
                            Returned = false
                        },
                        new
                        {
                            Id = 11,
                            Amount = 22,
                            AmountReturned = 0,
                            ItemId = 4,
                            PurchaseId = 6,
                            Returned = false
                        },
                        new
                        {
                            Id = 12,
                            Amount = 21,
                            AmountReturned = 0,
                            ItemId = 5,
                            PurchaseId = 6,
                            Returned = false
                        },
                        new
                        {
                            Id = 13,
                            Amount = 15,
                            AmountReturned = 0,
                            ItemId = 2,
                            PurchaseId = 7,
                            Returned = false
                        },
                        new
                        {
                            Id = 14,
                            Amount = 7,
                            AmountReturned = 0,
                            ItemId = 1,
                            PurchaseId = 7,
                            Returned = false
                        },
                        new
                        {
                            Id = 15,
                            Amount = 23,
                            AmountReturned = 0,
                            ItemId = 3,
                            PurchaseId = 8,
                            Returned = false
                        },
                        new
                        {
                            Id = 16,
                            Amount = 14,
                            AmountReturned = 0,
                            ItemId = 4,
                            PurchaseId = 8,
                            Returned = false
                        },
                        new
                        {
                            Id = 17,
                            Amount = 3,
                            AmountReturned = 0,
                            ItemId = 5,
                            PurchaseId = 9,
                            Returned = false
                        },
                        new
                        {
                            Id = 18,
                            Amount = 30,
                            AmountReturned = 0,
                            ItemId = 1,
                            PurchaseId = 9,
                            Returned = false
                        },
                        new
                        {
                            Id = 19,
                            Amount = 20,
                            AmountReturned = 0,
                            ItemId = 2,
                            PurchaseId = 10,
                            Returned = false
                        },
                        new
                        {
                            Id = 20,
                            Amount = 14,
                            AmountReturned = 0,
                            ItemId = 3,
                            PurchaseId = 10,
                            Returned = false
                        },
                        new
                        {
                            Id = 21,
                            Amount = 7,
                            AmountReturned = 0,
                            ItemId = 4,
                            PurchaseId = 11,
                            Returned = false
                        },
                        new
                        {
                            Id = 22,
                            Amount = 12,
                            AmountReturned = 0,
                            ItemId = 5,
                            PurchaseId = 11,
                            Returned = false
                        });
                });

            modelBuilder.Entity("RegisterManagement.Models.Inventory", b =>
                {
                    b.HasOne("RegisterManagement.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegisterManagement.Models.PurchaseItem", b =>
                {
                    b.HasOne("RegisterManagement.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegisterManagement.Models.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
